#spring:
#  datasource:
#    #    type: com.alibaba.druid.pool.DruidDataSource
#
#
#    #MySQL配置
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.56.10:3306/mall_sms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: root
#
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#
#  application:
#    name: gulimallcoupon
#
#
#mybatis-plus:
#  # configure mapper map file location
#  mapper-location: classpath:/mapper/**/*.xml
#  # primary key auto increment
#  global-config:
#    db-config:
#      id-type: auto
#
#
#server:
#  port: 7000


#all configuration is moved to nacos config. air